image: alpine

compile:
  stage: build
  script:
    - mkdir -p dist/
    - cp -r images/ dist/
    - cp index.html favicon.ico manifest.json dist/
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  dependencies:
    - compile
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - public