image: alpine

compile:
  stage: build
  script:
    - mkdir -p dist/
    - ls -la
    - cp css/ dist/
    - cp app.js dist/
    - cp index.html dist/
    - cp my.appcache dist/
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  dependencies:
    - compile
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - public 