image: alpine

compile:
  stage: build
  script:
    - echo 123
  artifacts:
    paths:
      - .

pages:
  stage: deploy
  dependencies:
    - compile
  script:
    - mkdir -p public/
    - cp {*.html,*.js,my.appcache,css/} public/
  artifacts:
    paths:
      - public 